from hand import render
from ops1 import SKIN

EXECUTOR_PAL = {'a': '#5d6270', 'h': '#3a3e48', 'H': '#272a31', 'D': '#17191e',
                'v': '#0b0c0f', 'L': '#c8ecff', 'l': '#6fbfff',
                'q': '#4d525e', 'c': '#33363e', 'C': '#22252b', 'n': '#121317',
                'M': '#b9c1cc', 'G': '#7b8390', 'g': '#e0e6ee', 't': '#4a3a2c', 'T': '#2e241b', 'r': '#6fbfff'}
EXECUTOR = [
    '......................gMMMMMg...',
    '......................MMMMMMMG..',
    '.........aahhhha......MgggggMG..',
    '.......aahhhhhhhha....MMMMMMMG..',
    '......ahhhhhhhhhhhha..GGGGGGGG..',
    '.....ahhhhhhhhhhhhhhh.....tT....',
    '.....hhhhhhhhhhhhhhhh.....tT....',
    '....Hhhhhhhhhhhhhhhhhh....tT....',
    '....HhhhvvvvvvvvvvvvvvH...tT....',
    '....HhhvLLLLLLLLLLLlvvH...tT....',
    '....DHhhvvvvvvvvvvvvvH....tT....',
    '....DHHhhhhhhhhhhhhhhH....tT....',
    '..aaqqqDHHHHHHHHHHHHDqqa..tT....',
    '.aqqqqqqqqqqqqqqqqqqqqqqa.tT....',
    '.qqqcccqqqqqqqqqqqqqcccqq.tT....',
    'aqqcccccqqqqqqqqqqqcccccqqhhh...',
    'qqqcccccqqqqrrrqqqqcccccqhhhh...',
    'qqccccccqqqqqqqqqqqccccccqhhh...',
    'qqcccccqqqqqqqqqqqqqccccq.......',
    '.hhhhhqqqqqnnnnnqqqqq...........',
    '.hhhhhqqqqqnnnnnqqqqq...........',
    '..hhh.cqqqqqqqqqqqqqc...........',
    '......CcccccccccccccC...........',
    '.......nnnnnnnnnnnnn............',
    '.......cccccC..ccccc............',
    '.......cccccC..ccccc............',
    '.......cccccC..ccccc............',
    '......qqqqqqC..qqqqqq...........',
    '......cccccc...ccccccc..........',
    '......nnnnnn...nnnnnnn..........',
    '......nnnnnn...nnnnnnn..........',
    '................................',
]

INCIN_PAL = {'a': '#a3896c', 'h': '#7d6650', 'H': '#5a4838', 'D': '#3b2f24',
             'v': '#1d1a17', 'L': '#ffb347', 'l': '#d86a1a',
             'q': '#9a8166', 'c': '#735e48', 'C': '#4f3f30', 'n': '#2a2420',
             'k': '#4a4e58', 'K': '#2c2f36', 'M': '#8a92a0', 'G': '#3a3e48',
             'f': '#ffd04a', 'F': '#ff8a1a', 'r': '#e2401a', 'y': '#fff3b0'}
INCINERATOR = [
    '................................',
    '................................',
    '............aahhha..............',
    '..........aahhhhhhha............',
    '.........ahhhhhhhhhhha..........',
    '........ahhhhhhhhhhhhhh.........',
    '.......ahhhhhhhhhhhhhhhh........',
    '.......hhhhhhhhhhhhhhhhhh.......',
    '......Hhhhhvvvvhhhhhvvvvh.......',
    '......HhhhvLLLlvhhhvLLLlv.......',
    '......HhhhvLllLvhhhvLllLv.......',
    '......HhhhhvvvvhhhhhvvvvH.......',
    '......DHhhhhhhhvvvvhhhhH........',
    '......DHhhhhhhvkkkkvhhH.........',
    '.......DHhhhhhvkKKkvhH..........',
    '........DHHhhhhvvvvHH...........',
    '..kkk.....DDHHHHHDD.............',
    '.kKKKk...cqqqqqqqqqc............',
    '.kKMKk..cqqqqqqqqqqqc...........',
    '.kKMKk.cqqqcqqqqqqcqqc..........',
    '.kKMKkcqqcqqqqqqqqqcqcGGG.......',
    '.kKKKkcqqcqqnnnnnnnccMMMMMMMr...',
    '.kKKKkcCcqqqqqqqqqccGGGGGGGFrr..',
    '..kkk.cCcqqqqqqqqqcc....FFfrFr..',
    '.......CCcccccccccc....FfyfFFr..',
    '........nnnnnnnnnnn.....FffFr...',
    '........cccC..cccc.......FFr....',
    '........cccC..cccc..............',
    '.......nnnnC..nnnnn.............',
    '.......nnnnn..nnnnnn............',
    '.......nnnnn..nnnnnn............',
    '................................',
]

INFIL_PAL = {'a': '#3e4656', 'h': '#2a313d', 'H': '#1d222b', 'D': '#13161c',
             'v': '#0a0b0e', 'L': '#7ff6ff', 'l': '#2fc8e0',
             'q': '#344050', 'c': '#252d38', 'C': '#1a1f27', 'd': '#2e3846', 'n': '#101216',
             'g': '#dbe2ec', 'G': '#8d97a6', 'x': '#2fc8e0'}
INFILTRATOR = [
    '................................',
    '................................',
    '................................',
    '...........aahhha...............',
    '.........aahhhhhhha.............',
    '........ahhhhhhhhhhha...........',
    '.......ahhhhhhhhhhhhhh..........',
    '......ahhhhhhhhhhhhhhhh.........',
    '......hhhhhhhhhhhhhhhhhh........',
    '.....Hhhhhhhvvvvvvvvvvvv........',
    '.....HhhhhhvvvvvvvvvvvvvH.......',
    '.....HhhhhhvvLlvvvvvLlvvH.......',
    '.....DHhhhhvvvvvvvvvvvvvH.......',
    '.....DHHhhhhvvvvvvvvvvvH........',
    '......DHHhhhhhhhhhhhhhH.........',
    '.......DHHhhhhhhhhhhHH..........',
    '.........DDHHHHHHHHD............',
    '..........cqdqdqdqdc............',
    '.........cqdqdqdqdqqc...........',
    '........cqdqcdqdqdcxqc..........',
    '........cqdcqdqdqdqcxc..........',
    '........cqqcnnnnnnnncqcgg.......',
    '........hhCcdqdqdqdqcqhhgg......',
    '........hhCcqdqdqdqdcc...gGg....',
    '.........CCcccccccccc.....gG....',
    '..........nnnnnnnnnnn...........',
    '..........cdcC..cdcc............',
    '..........cdcC..cdcc............',
    '.........nnnnC..nnnnn...........',
    '.........nnnnn..nnnnnn..........',
    '.........nnnnn..nnnnnn..........',
    '................................',
]

MEDIC_PAL = {'a': '#ffffff', 'h': '#e6e9ef', 'H': '#b4bbc6', 'D': '#7d8592',
             'v': '#15171d', 'L': '#c8ecff', 'l': '#6fbfff',
             'q': '#ffffff', 'c': '#e3e7ee', 'C': '#aab1bd', 'n': '#2a2d35',
             'b': '#4fb0ff', 'B': '#2a70c8', 'u': '#f4f6f9', 'U': '#9aa2ae'}
MEDIC = [
    '................................',
    '................................',
    '............aahhha..............',
    '..........aahhhbhhha............',
    '.........ahhhhbbbhhhha..........',
    '........ahhhhhhbhhhhhhh.........',
    '.......ahhhhhhhhhhhhhhhh........',
    '.......hhhhhhhhhhhhhhhhhh.......',
    '......Hhhhhhhhhhhhhhhhhhh.......',
    '......Hhhhhhhhhhhhhhhhhhhh......',
    '......HhhhvvvvvvvvvvvvvvvH......',
    '......HhhvvLLLLlvvvvvLLLlv......',
    '......HhhvvvvvvvvvvvvvvvvH......',
    '......DHhhvvvvvvvvvvvvvvH.......',
    '......DHhhhhhhhhhhhhhhhhH.......',
    '.......DHhhhhHHHHHHHHhhH........',
    '........DHHhhhhhhhhhhHH.........',
    '..........DDHHHHHHHDD...........',
    '..........cqqqqqqqqqc...........',
    '.........cqqqqqbqqqqqc..........',
    '........cqqqcqbbbqqcqqc.........',
    '........cqqcqqqbqqqqcqc.........',
    '........cqqcnnnnnnnncqcuuuu.....',
    '........ccCcqqqqqqqqccuubuuU....',
    '........ccCcqqqqqqqqccubbbuU....',
    '.........CCccccccccccuubuuU.....',
    '..........nnnnnnnnnnn.UUUU......',
    '..........cccC..cccc............',
    '..........cccC..cccc............',
    '.........nnnnC..nnnnn...........',
    '.........nnnnn..nnnnnn..........',
    '.........nnnnn..nnnnnn..........',
]

ARMORED_PAL = {'a': '#f4f6f9', 'h': '#d3d8e0', 'H': '#a3aab6', 'D': '#6e7683',
               'v': '#15171d', 'L': '#c8ecff', 'l': '#6fbfff',
               'M': '#8a92a0', 'G': '#4a4f59', 'n': '#1d1f25', 'N': '#3a3d46', 'w': '#5c6270'}
ARMORED = [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '..........aahhhhhha.............',
    '........aahhhhhhhhhhaa..........',
    '.......ahhhhvvvLLlhhhhMMMMMMMMMM',
    '.......hhhhhhhhhhhhhhhGGGGGGGGGG',
    '.......HhhhhhhhhhhhhhhH.........',
    '....aaaHHHHHHHHHHHHHHHHaaaa.....',
    '..aahhhhhhhhhhhhhhhhhhhhhhhha...',
    '.ahhhhhhhhhhhhhhhhhhhhhhhhhhha..',
    '.hhhhhhhhvvvvvvvvvvhhhhhhhhhhhh.',
    '.hhhhhhhhvLLLLLLLlvhhhhhhhhhhhh.',
    '.HhhhhhhhvvvvvvvvvvhhhhhhhhhhhH.',
    '.HHhhhhhhhhhhhhhhhhhhhhhhhhhHHH.',
    '.DHHHHHHHHHHHHHHHHHHHHHHHHHHHHD.',
    '..DDDDDDDDDDDDDDDDDDDDDDDDDDDD..',
    '..nNNNNNNNNNNNNNNNNNNNNNNNNNNn..',
    '.nNwwNwwNwwNwwNwwNwwNwwNwwNwwNn.',
    '.nNwMwNwMwNwMwNwMwNwMwNwMwNwMNn.',
    '.nNwwNwwNwwNwwNwwNwwNwwNwwNwwNn.',
    '..nNNNNNNNNNNNNNNNNNNNNNNNNNNn..',
    '...nnnnnnnnnnnnnnnnnnnnnnnnnn...',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
]

CLERIC_PAL = {**SKIN,
              'a': '#3a3a48', 'h': '#1d1d26', 'H': '#121218', 'D': '#09090c',
              'i': '#8fdcff', 'I': '#2f6fa8',
              'q': '#2c2c36', 'c': '#18181e', 'C': '#0c0c10', 'x': '#f4f4f6', 'X': '#b8bcc6',
              'n': '#0a0a0d', 'M': '#c9d1db', 'G': '#6a727f', 'g': '#9aa2ae'}
CLERIC = [
    '................................',
    '................................',
    '............aahha...............',
    '..........aahhhhhhha............',
    '.........ahhhhhhhhhhha..........',
    '........ahhhhhhhhhhhhha.........',
    '........hhhhhhhhhhhhhhhh........',
    '.......Hhhhhhhhhhhhhhhhhh.......',
    '.......HhhhhhhhhhhhhhHhhh.......',
    '......HHhhhhHsssssssssHhH.......',
    '......HHhhhsssssssssssssH.......',
    '......DHhhssssssssssssssH.......',
    '......DHhhsseesssssssseeS.......',
    '......DHhhssIissssssssIiS.......',
    '.......DHhssssssssssssssS.......',
    '........HhSsssssssmmsssS........',
    '.........HSSssssssssSSS.........',
    '..........xxxSSSSSSxxx..........',
    '.........qxXxccccccxXxq.........',
    '........qcxxccccccccxxcq........',
    '.......qccccccccccccccccq.......',
    '.......qccccccqqccccccccq.......',
    '......qcccccccqqcccccMMMMMG.....',
    '......qcccccsscqcccssMGGG.......',
    '......qcccccsMMMMMG.cc..........',
    '.....qccccccc.MGGG..ccq.........',
    '.....qcccccccccqqccccccq........',
    '....qccccccc.ccqqcc.ccccq.......',
    '....qcccccc..cccqcc..cccq.......',
    '...qcccccc...nnnn.nnnn.ccq......',
    '...ccccccC...nnnn.nnnnn.cC......',
    '....CCCCC....nnnn.nnnnn.........',
]

SPRITES = [('Executor', EXECUTOR, EXECUTOR_PAL), ('Incinerador', INCINERATOR, INCIN_PAL),
           ('Infiltrado', INFILTRATOR, INFIL_PAL), ('Enfermeiro', MEDIC, MEDIC_PAL),
           ('Blindado', ARMORED, ARMORED_PAL), ('Clérigo (boss)', CLERIC, CLERIC_PAL)]

if __name__ == '__main__':
    from sheet import sheet
    sheet([(n, render(r, p)) for n, r, p in SPRITES], 'enemies2.png', cols=6)
