from hand import render

HELM = {'a': '#ffffff', 'h': '#dfe3ea', 'H': '#aeb5c1', 'D': '#7b8390',
        'v': '#15171d', 'L': '#c8ecff', 'l': '#6fbfff'}
UNIF = {'q': '#f1f3f7', 'c': '#cfd5de', 'C': '#9aa2af', 'n': '#2a2d35', 'N': '#41454f', 'g': '#3a3d46'}

HELMET_ROWS = [
    '................................',
    '................................',
    '............aahhha..............',
    '..........aahhhhhhha............',
    '.........ahhhhhhhhhhha..........',
    '........ahhhhhhhhhhhhhh.........',
    '.......ahhhhhhhhhhhhhhhh........',
    '.......hhhhhhhhhhhhhhhhhh.......',
    '......Hhhhhhhhhhhhhhhhhhh.......',
    '......Hhhhhhhhhhhhhhhhhhhh......',
    '......HhhhvvvvvvvvvvvvvvvH......',
    '......HhhvvLLLLlvvvvvLLLlv......',
    '......HhhvvvvvvvvvvvvvvvvH......',
    '......DHhhvvvvvvvvvvvvvvH.......',
    '......DHhhhhhhhhhhhhhhhhH.......',
    '.......DHhhhhHHHHHHHHhhH........',
    '........DHHhhhhhhhhhhHH.........',
    '..........DDHHHHHHHDD...........',
]

PEACEKEEPER_PAL = {**HELM, **UNIF, 'x': '#1d1f25', 'X': '#43474f'}
PEACEKEEPER = HELMET_ROWS + [
    '..........cqqqqqqqqqc...........',
    '.........cqqqqqqqqqqqc..........',
    '........cqqqcqqqqLqcqqc.........',
    '........cqqcqqqqqqqqcqc.........',
    '........cqqcnnnnnnnnccqgg.......',
    '........ggCcqqqqqqqqccqggX......',
    '........ggCcqqqqqqqqcc...xX.....',
    '.........CCcccccccccc.....xX....',
    '..........nnnnnnnnnnn......xL...',
    '..........cccC..cccc........l...',
    '..........cccC..cccc............',
    '.........nnnnC..nnnnn...........',
    '.........nnnnn..nnnnnn..........',
    '.........nnnnn..nnnnnn..........',
]

HOUND_PAL = {'a': '#6a707d', 'h': '#41454f', 'H': '#2a2d34', 'D': '#1b1d22',
             'v': '#9aa4b4', 'V': '#6c7586', 'L': '#8fdcff', 'n': '#111215', 'w': '#e8eef6'}
HOUND = [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '......................a.........',
    '.....................aha........',
    '....................ahhha.......',
    '...................ahhhhhh......',
    '...................hhhLhhhhh....',
    '..................HhhhhhhhhhhH..',
    '..a...............HhhhhhhhhhHHn.',
    '..aa..............HHhhhhhhwwH...',
    '...ah......aaaaaahhhhhhhHHHw....',
    '....hhaaaahhhhhhhhhhhhhhH.......',
    '....hhhhhhhhhhhhhhhhhhhH........',
    '....HhhvvvvvvvvvvvvhhhH.........',
    '....HHhvVVVVVVVVVVvhhH..........',
    '.....HHhhhhhhhhhhhhhHH..........',
    '.....HHhh.Hhh...HhhHH...........',
    '.....Hhh..Hh.....HhhH...........',
    '....Hhh...Hh......Hhh...........',
    '....Hh....Hh......Hh............',
    '...HHh...HHh.....HHh............',
    '...DDD...DDD.....DDD............',
    '................................',
    '................................',
    '................................',
]

RIOT_PAL = {'a': '#5a5f6b', 'h': '#33363f', 'H': '#22242b', 'D': '#15161b',
            'v': '#0d0e12', 'L': '#c8ecff', 'l': '#6fbfff',
            'q': '#4a4e59', 'c': '#30333b', 'C': '#1f2127', 'n': '#14151a', 'g': '#3a3d46',
            'x': '#e4f1ff', 'u': '#a9c6e8', 'U': '#6d8fb8', 'S': '#4a6a94'}
RIOT = [
    '................................',
    '................................',
    '............aahhha..............',
    '..........aahhhhhhha............',
    '.........ahhhhhhhhhhha..........',
    '........ahhhhhhhhhhhhhh.........',
    '.......ahhhhhhhhhhhhhhhh........',
    '.......hhhhhhhhhhhhhhhhhh.......',
    '......Hhhhhhhhhhhhhhhhhhh.......',
    '......HhhhvvvvvvvvvvvvvvvH......',
    '......HhhvvLLLLlvvvvvLLLlv......',
    '......HhhvvvvvvvvvvvvvvvvH......',
    '......DHhhvvvvvvvvvvvvxxxxxxxx..',
    '......DHhhhhhhhhhhhhhxuuuuuuuuU.',
    '.......DHhhhhHHHHHHHxuuuuuuuuuU.',
    '........DHHhhhhhhhhhxuuvvvvvvuU.',
    '..........DDHHHHHHHDxuuuuuuuuuU.',
    '..........cqqqqqqqqqxuuuuuuuuuU.',
    '.........cqqqqqqqqqqxuuuuuuuuuU.',
    '........cqqqcqqqqqqcxuuuuuuuuuU.',
    '........cqqcqqqqqqqqxuuuuuuuuuU.',
    '........cqqcqqnnnnnnxuuuuuuuuuU.',
    '........ggCcqqqqqqqqxuuuuuuuuuU.',
    '........ggCcqqqqqqqqxuuuuuuuuuU.',
    '.........CCcccccccccxuuuuuuuuuU.',
    '..........nnnnnnnnnnxuuuuuuuuuU.',
    '..........cccC..cccxuuuuuuuuuuU.',
    '..........cccC..cccxuuuuuuuuuuU.',
    '.........nnnnC..nnnnSUUUUUUUUU..',
    '.........nnnnn..nnnnnn..........',
    '.........nnnnn..nnnnnn..........',
    '................................',
]

RIFLE_PAL = {**HELM, 'q': '#c9ced8', 'c': '#a4abb8', 'C': '#767e8c', 'n': '#2a2d35', 'g': '#3a3d46',
             'M': '#6a717e', 'G': '#2c2f36', 'w': '#4a4e58', 't': '#4a3a2c'}
RIFLEMAN = HELMET_ROWS + [
    '..........cqqqqqqqqqc...........',
    '.........cqqqqqqqqqqqc..........',
    '........cqqqcqqqqLqcqqc.........',
    '........cqqcqqqqqqqqcqcgg.......',
    '........cqqcnnnnnnnnccMMMMMMMMMM',
    '........ggCcqqqqqqqctwwwwwwwwGGG',
    '........ggCcqqqqqqqqttG..G......',
    '.........CCcccccccccc...........',
    '..........nnnnnnnnnnn...........',
    '..........cccC..cccc............',
    '..........cccC..cccc............',
    '.........nnnnC..nnnnn...........',
    '.........nnnnn..nnnnnn..........',
    '.........nnnnn..nnnnnn..........',
]

DRONE_PAL = {'a': '#ffffff', 'h': '#e2e6ec', 'H': '#b0b7c2', 'D': '#7d8592',
             'n': '#3a3d46', 'r': '#c9d0da', 'v': '#15171d', 'L': '#8fdcff', 'l': '#2f8fd8', 'w': '#ffffff'}
DRONE = [
    '................................',
    '................................',
    '................................',
    '................................',
    '...rrrrrrrr........rrrrrrrr.....',
    '.......n..............n.........',
    '.......n..............n.........',
    '......nnn............nnn........',
    '......nnhhhhhhhhhhhhhhnn........',
    '.....aahhhhhhhhhhhhhhhhhh.......',
    '....ahhhhhhhhhhhhhhhhhhhhH......',
    '....hhhhhhhhhvvvvvhhhhhhhH......',
    '....HhhhhhhhvvLLLvvhhhhhHH......',
    '.....HHhhhhhvLLwLlvhhhHHD.......',
    '......DHHHHHvlLLlvvHHHDD........',
    '........DDDDDvvvvvDDDD..........',
    '.............n...n..............',
    '............n.....n.............',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
]

GUNSHIP_PAL = {'a': '#7b8290', 'h': '#525865', 'H': '#383d47', 'D': '#24272e',
               'n': '#1d1f25', 'r': '#9aa2ae', 'v': '#0d0e12', 'L': '#ff7a7a', 'l': '#d0262e', 'w': '#ffe0e0',
               'M': '#8a92a0', 'G': '#3a3e48', 'y': '#f2c94c'}
GUNSHIP = [
    '................................',
    '................................',
    '................................',
    '..rrrrrrrr..............rrrrrrrr',
    '......n....................n....',
    '......n....................n....',
    '.....nnn..................nnn...',
    '.....nnhhhhhhhhhhhhhhhhhhhhnn...',
    '....aahhhhhhhhhhhhhhhhhhhhhhh...',
    '...ahhhhhhhhhhhhhhhhhhhhhhhhhH..',
    '...hhhhhhhhhhhhhhvvvvvhhhhhhhH..',
    '...HhhhyhhhhhhhhvvLLLvvhhhhhhH..',
    '...HHhhhhhhhhhhhvLLwLlvhhhhhHH..',
    '....HHHhhhhhhhhhvlLLlvvhhhHHD...',
    '.....DHHHHHHHHHHHvvvvvHHHHDD....',
    '......DDnnnnnnnnnnnnnnnnnDD.....',
    '.......MMMMMMMG....MMMMMMMG.....',
    '.......GGGGGGGG....GGGGGGGG.....',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
]

SPRITES = [('Pacificador', PEACEKEEPER, PEACEKEEPER_PAL), ('Cão de Patrulha', HOUND, HOUND_PAL),
           ('Escudo de Choque', RIOT, RIOT_PAL), ('Fuzileiro', RIFLEMAN, RIFLE_PAL),
           ('Drone', DRONE, DRONE_PAL), ('Drone de Assalto', GUNSHIP, GUNSHIP_PAL)]

if __name__ == '__main__':
    from sheet import sheet
    sheet([(n, render(r, p)) for n, r, p in SPRITES], 'enemies1.png', cols=6)
