from hand import render

SKIN = {'s': '#f8d5bb', 'S': '#e2a98c', 'e': '#2b1d2f', 'w': '#ffffff', 'm': '#a64c45', 'b': '#f5a49a'}
LEGS = {'p': '#2f2c36', 'P': '#1f1d25', 'k': '#26232b', 'K': '#4a4553'}

FAISCA_PAL = {**SKIN, **LEGS,
    'a': '#fff3b0', 'h': '#f2c64a', 'H': '#c48f26', 'D': '#7a5418',
    'i': '#ff9a3a', 'I': '#b0501a',
    'n': '#3b3030', 'L': '#6fd0ff', 'l': '#d8f6ff',
    'q': '#7a6a60', 'c': '#54473f', 'C': '#352c27',
    'y': '#ffc080', 'r': '#f2802c', 'R': '#a8481a', 'z': '#f2f0ea',
    'g': '#e7edf4', 'G': '#8d97a6', 't': '#3b3030'}
FAISCA = [
    '................................',
    '..........a....a....a...........',
    '.........aha..aha..aha..........',
    '........ahhhaahhhaahhha.........',
    '.......ahhhhhhhhhhhhhhhha.......',
    '......ahhhhhhhhhhhhhhhhhha......',
    '......hhhhhhhhhhhhhhhhhhhh......',
    '.....Hhhhhhhhhhhhhhhhhhhhh......',
    '.....HhnnnLLlnnnnnLLlnnnhh......',
    '....HHhnnnLLLnnnnnLLLnnnHh......',
    '....HHhhhHsHhhhhsHhhhHssHh......',
    '...HHHhhsssshssssssssssH........',
    '...HHhhhsseessssssssseesH.......',
    '...DHhhhssiwssssssssiwssS.......',
    '...DHHhhssIissssssssIissS.......',
    '....DHhhbsssssssssssssbs........',
    '.....DHhSssssssmsssssssS........',
    '.......HDSSssssssssSSS..........',
    '...........cyyccccyyc...........',
    '..........ccyrrcccrrcc..........',
    '.........qccyrczzzcrccq.........',
    '.........qccyrczzzcrcccq........',
    '.........qccrRczzzcRcccqss.g....',
    '.........sscrRcnnncRccccsstgg...',
    '.........sSCrRcnnncRccc...tggg..',
    '..........CcRcccccccRc.....gGGg.',
    '...........ppppppppppp..........',
    '...........pppP...pppp..........',
    '...........pppP...pppp..........',
    '..........KkkkP...Kkkkk.........',
    '..........Kkkkk...Kkkkkk........',
    '..........kkkkk...kkkkkk........',
]

MURALHA_PAL = {**SKIN, **LEGS,
    'a': '#6a6175', 'h': '#45404f', 'H': '#2f2b37', 'D': '#1f1c25',
    'i': '#6a8fd0', 'I': '#34508a',
    'v': '#d5dbe4', 'q': '#a7b0bd', 'c': '#7b8492', 'C': '#555d6a',
    'u': '#8a94a2', 'U': '#5a6370', 'x': '#c4cbd6',
    'r': '#cc3138', 'R': '#8c1d27', 'y': '#f06363', 'n': '#3e3a48'}
MURALHA = [
    '................................',
    '................................',
    '................................',
    '...........aahhhha..............',
    '.........aahhhhhhhhha...........',
    '........ahhhhhhhhhhhhha.........',
    '.......ahhhhhhhhhhhhhhhh........',
    '.......hhhhhhhhhhhhhhhhhh.......',
    '......Hhhhhhhhhhhhhhhhhhh.......',
    '......HhhhHhhhhhHhhhhhHhh.......',
    '......HhhHsHhhhsHhhhhssHh.......',
    '......HhhsssshssssssssssH.......',
    '......HhhsseesssssssseesH.......',
    '......DHhssiwssssssssiwsS.......',
    '......DHhssIisssssssssIiS.......',
    '.......DHhbsssssssssssbs........',
    '........HSssssssmssssssS........',
    '.........SSSssssssssSSS.........',
    '.........vvqqqqqqqqqvv..........',
    '........vqqcccccccccqqv.xxxxxxx.',
    '.......vqcccvqqqqqvcccqxuuuuuuuU',
    '.......qcccqvccccccvccxuuuyrruuU',
    '.......qccqqcnnnnnnccxuuuyrrruuU',
    '.......sscqccccccccccxuuuurrRuuU',
    '.......sSCcqcccccccccxuuuuRRuuuU',
    '........CCcccccccccccxuuuuuuuuuU',
    '..........ppppppppppxuuuuuuuuuuU',
    '..........pppP..ppppxuuuuuuuuuuU',
    '..........pppP..pppp.UUUUUUUUUU.',
    '.........vqqqP..vqqqq...........',
    '.........vqccc..vqcccc..........',
    '.........CCCCC..CCCCCC..........',
]

BASTIAO_PAL = {**SKIN, **LEGS,
    'a': '#a07a58', 'h': '#7a5638', 'H': '#563a24', 'D': '#3a2616',
    'i': '#4fa36a', 'I': '#2a6a3e',
    'v': '#f2cf8a', 'q': '#d9a75c', 'c': '#a87a3e', 'C': '#6e4e26',
    'l': '#8a5a3a', 'L': '#5e3c24',
    'g': '#dfe5ee', 'G': '#8d97a6', 'M': '#5b6370', 't': '#6b4a33',
    'r': '#cc3138', 'R': '#8c1d27', 'u': '#9b6a3e', 'U': '#5c3c20', 'x': '#c8955a'}
BASTIAO = [
    '................................',
    '................................',
    '...........................gg...',
    '...........aahhha.........gMMg..',
    '.........aahhhhhhha......gMggMg.',
    '........ahhhhhhhhhha......gMMg..',
    '.......ahhhhhhhhhhhhh......gg...',
    '.......hhhhhhhhhhhhhhh.....tt...',
    '......Hhhhhhhhhhhhhhhhh....tt...',
    '......HhhhHhhhhHhhhhhHh....tt...',
    '......HhhHsHhhhsHhhhhssH...tt...',
    '......HhhsssshsssssssssH...tt...',
    '......HhhsseesssssssseesH..tt...',
    '......DHhssiwssssssssiwsS..tt...',
    '......DHhssIisssssssssIiS..tt...',
    '.......DHhbsssssssssssbs..sst...',
    '........HSssssssmssssssS..sst...',
    '.........SSSssssssssSSS...cc....',
    '.........vvqqqqqqqqqvv...qc.....',
    '...xxx..vqqcccccccccqqv.qc......',
    '..xuuux.vqcccvqqqqqvccqqc.......',
    '.xuuruux.cccqvllllllvccc........',
    '.xurrrux.ccqqcllllllcccc........',
    '.xuuRuux.cqqccLLLLLLcccc........',
    '..xuuux.sSCcqcccccccccc.........',
    '...xxx...CCcccccccccc...........',
    '..........ppppppppppp...........',
    '..........pppP..ppppp...........',
    '..........pppP..ppppp...........',
    '.........lllLP..llllll..........',
    '.........llllL..lllllll.........',
    '.........LLLLL..LLLLLLL.........',
]

LIRIO_PAL = {**SKIN, **LEGS,
    'a': '#ffffff', 'h': '#e6dff2', 'H': '#b9add0', 'D': '#8a7fa6',
    'i': '#3fc286', 'I': '#1f7a52',
    'q': '#ffffff', 'c': '#e9ebf1', 'C': '#b9bdca',
    'r': '#d6333b', 'R': '#8c1d27',
    'u': '#f4f4f6', 'U': '#a9adb8', 'n': '#5a5566'}
LIRIO = [
    '................................',
    '................................',
    '............aaaahh..............',
    '..........aahhhhhhhha...........',
    '.........ahhhhhhhhhhhha.........',
    '........ahhhhhhhhhhhhhha........',
    '.......ahhhhhhhhhhhhhhhhh.......',
    '.......hhhhhhhhhhhhhhhhhhh......',
    '......Hhhhhhhhhhhhhhhhhhhh......',
    '......HhhhHhhhhhHhhhhhhHhh......',
    '.....HHhhHsHhhhhsHhhhhssHhH.....',
    '.....HHhhsssshssssssssssHhH.....',
    '.....HHhhsseessssssssseesHhH....',
    '.....DHhhssiwssssssssiwssHhH....',
    '.....DHhhssIisssssssssIisHhH....',
    '.....DHhhbsssssssssssssbsHhD....',
    '.....DHhhHSssssssmssssssSHD.....',
    '.....DHhh..SSSssssssssSSHhD.....',
    '.....DHh...qqqqqqqqqqqq.HhD.....',
    '.....DH...qqccccccrccccq.D......',
    '.....D...qcccccccrrrcccccq......',
    '.........qrrccccccrcccccq.......',
    '.........qRRccccccccccccq.......',
    '.........qcccccccrcccccccuuuu...',
    '.........sscccccccccccccuurruU..',
    '.........sSCccccccccccccurrrrU..',
    '..........CcccccccccccccuuruuU..',
    '..........CCcccccccccccc.UUUU...',
    '...........ppppP...pppp.........',
    '..........KkkkkP...Kkkkk........',
    '..........Kkkkkk...Kkkkkk.......',
    '..........kkkkkk...kkkkkk.......',
]

SPRITES = [('Faísca', FAISCA, FAISCA_PAL), ('Muralha', MURALHA, MURALHA_PAL), ('Bastião', BASTIAO, BASTIAO_PAL), ('Lírio', LIRIO, LIRIO_PAL)]

if __name__ == '__main__':
    from sheet import sheet
    import brasa
    items = [('Brasa', render(brasa.ROWS, brasa.PAL))] + [(n, render(r, p)) for n, r, p in SPRITES]
    sheet(items, 'ops1.png', cols=5)
