from hand import render
from ops1 import SKIN, LEGS

CORVO_PAL = {**SKIN, **LEGS,
    'a': '#4a4658', 'h': '#25222d', 'H': '#17151d', 'D': '#0e0d12',
    'i': '#9aa3b5', 'I': '#4e5668',
    'q': '#3a3644', 'c': '#22202a', 'C': '#16141b',
    'y': '#f06363', 'r': '#cc3138', 'R': '#8c1d27',
    'g': '#5e6573', 'G': '#3a3f4a', 'M': '#8a92a0', 't': '#5a3e2a', 'T': '#3c2a1c', 'L': '#7fd6ff'}
CORVO = [
    '................................',
    '................................',
    '..........a.aaahh...............',
    '.........ahahhhhhhha............',
    '........ahhhhhhhhhhhha..........',
    '.......ahhhhhhhhhhhhhhh.........',
    '......ahhhhhhhhhhhhhhhhh........',
    '......hhhhhhhhhhhhhhhhhhh.......',
    '.....HhhhhhhhhhhhhhhhhhhhH......',
    '....HHhhhhHhhhhHhhhhhHhhhH......',
    '...HHhhhhHsHhhhsHhhhhssHhH......',
    '..HHhhhhsssshssssssssssHH.......',
    '..HHhhhhsseesssssssseesH........',
    '...DHhhhssiwssssssssiwsS........',
    '...DHHhhssIissssssssIisS........',
    '....DHHhbsssssssssssssbs........',
    '.....DHhSsssssssmssssssS........',
    '.......HDSSyyrrrrrrrSS..........',
    '..........ryyrrrrrrrr...........',
    '.........crryrrrrrrrRc..........',
    '........qcrrRRrrrrRRccq.........',
    '........qccRRcqcccccccqss.......',
    '........qcRcqccccccccggMMMMMMMMM',
    '.......qcRccqcccccccTtGGgggggggg',
    '.......sscRcqccccccsTtG.L.......',
    '.......sSCRcqcccccccTT..........',
    '.......CCcRcqcccccccc...........',
    '.......CCCcccccccccccc..........',
    '..........ppppP...pppp..........',
    '..........KkkkP...Kkkkk.........',
    '..........Kkkkk...Kkkkkk........',
    '..........kkkkk...kkkkkk........',
]

FALCAO_PAL = {**SKIN, **LEGS,
    'a': '#e4e4e8', 'h': '#a9a9b2', 'H': '#77777f', 'D': '#4e4e56',
    'i': '#e0b23a', 'I': '#8a6418',
    'n': '#3b3030', 'L': '#ffb347', 'l': '#ffe2a8',
    'q': '#7c6d58', 'c': '#5a4f40', 'C': '#3b342a',
    'y': '#f06363', 'r': '#cc3138', 'R': '#8c1d27',
    'g': '#6a7280', 'G': '#40454f', 'M': '#a0a8b5', 't': '#5a3e2a'}
FALCAO = [
    '................................',
    '................................',
    '................................',
    '...........aahha................',
    '.........aahhhhhhha.............',
    '........ahhhhhhhhhha............',
    '.......ahhhhhhhhhhhhh...........',
    '.......hhhhhhhhhhhhhhh..........',
    '......HhnnnnLLlnnnnLLlh.........',
    '......HhnnnnLLLnnnnLLLh.........',
    '......HhhHsHhhhsHhhhhssH........',
    '......HhhsssshsssssssssH........',
    '......HhhsseesssssssseesH.......',
    '......DHhssiwssssssssiwsS......M',
    '......DHhssIisssssssssIiS.....Mg',
    '.......DHhbsssssssssssbs.....MgG',
    '........HSssssssmssssssS....MgG.',
    '.........SSSssssssssSSS....MgG..',
    '.........qqrrrrrrrrrqq....MgG...',
    '........qqcrrcccccrrcq...MgG....',
    '.......qcccrcqqqqqcrccq.MgG.....',
    '.......qcccccqccccccccqMgG......',
    '.......qcccccqnnnnnnccMgG.......',
    '.......sscccccccccccctgGs.......',
    '.......sSCcccccccccccct.........',
    '........CCcccccccccccc..........',
    '..........ppppppppppp...........',
    '..........pppP..ppppp...........',
    '..........pppP..ppppp...........',
    '.........KkkkP..Kkkkkk..........',
    '.........Kkkkk..Kkkkkkk.........',
    '.........kkkkk..kkkkkkk.........',
]

TROVAO_PAL = {**SKIN, **LEGS,
    'a': '#9aa46a', 'h': '#6f7a45', 'H': '#4c5530', 'D': '#323a1f',
    'f': '#7a5a3a', 'F': '#553d26',
    'i': '#d0763a', 'I': '#7a3a14',
    'q': '#8a9460', 'c': '#626b41', 'C': '#41482b',
    'y': '#f06363', 'r': '#cc3138', 'R': '#8c1d27',
    'g': '#5c6270', 'G': '#3a3e48', 'M': '#8a92a0', 'x': '#2a2c32', 'o': '#ffb347', 'n': '#3b3030'}
TROVAO = [
    '................................',
    '................................',
    '................................',
    '...........aaahhha..............',
    '.........aahhhhhhhha............',
    '........ahhhhhhhhhhhha..........',
    '.......ahhhhhhhhhhhhhhh.........',
    '.......hhhhhhhhhhhhhhhhh........',
    '......HhhhhhhhhhhhhhhhhhH.......',
    '......HHHHHHHHHHHHHHHHHHH.......',
    '......FffffsffffssfffssfF.......',
    '......FffsssssssssssssssF.......',
    '......Fffsseessssssseess........',
    '......DFfssiwsssssssiwsS........',
    '......DFFssIissssssssIiS........',
    '.......DFfbsssssssssssbs........',
    '........FSssssssmssssssS........',
    '.........SSSssssssssSSS.........',
    '..MMMMMMMMMMMMMMMMMMMMMMMMMMMr..',
    '.MgggggggggggggggggggggggggggRx.',
    '.MGGGGGGGGGGGGGGGGGGGGGGGGGGGRx.',
    '..xx...qcccccccccq....xx....rr..',
    '.......qccccrcccccq.............',
    '.......qcccnnnnnnnccq...........',
    '.......qcccooooooocccq..........',
    '.......sscccccccccccss..........',
    '.......sSCcccccccccccS..........',
    '..........ppppppppppp...........',
    '..........pppP..ppppp...........',
    '.........KkkkP..Kkkkkk..........',
    '.........Kkkkk..Kkkkkkk.........',
    '.........kkkkk..kkkkkkk.........',
]

SPRITES = [('Corvo', CORVO, CORVO_PAL), ('Falcão', FALCAO, FALCAO_PAL), ('Trovão', TROVAO, TROVAO_PAL)]

if __name__ == '__main__':
    from sheet import sheet
    import ops1
    items = [(n, render(r, p)) for n, r, p in ops1.SPRITES[0::3]] + [(n, render(r, p)) for n, r, p in SPRITES]
    sheet(items, 'ops2.png', cols=5)
